### ISSUE TITLE
Ruby version too high

### ISSUE THREAD

**Issue by crondaemon** [pwelch/virustotal_api#29]
Hi
The last version (0.5.0) requires ruby 2.6 while the previous required 2.4. However ubuntu 18.04 LTS ships with ruby 2.5. This ubuntu release will last until 2023, so basically those users will be prevented to use the 0.5.0 version unless you relax the requirement and downgrade it to 2.5. Would you consider doing that? Otherwise I guess ubuntu 18.04 users will be forced to install a vanilla version of ruby (unlikely) or stop using your gem and access API via straight calls.

**Comment by crondaemon** [comment]
Hey @pwelch, any thought on this proposal? Thanks!

**Comment by pwelch** [comment]
@crondaemon I put 2.6 because Ruby says 2.5 is EOL: https://www.ruby-lang.org/en/downloads/

Most people install their own latest Ruby anyways but if you think it's better to support 2.5 a little longer I'm okay changing it to 2.5. Thoughts?

**Comment by crondaemon** [comment]
A lot of people rely on distribution ruby. The one shipped with ubuntu 18.04 LTS is 2.5, that is going to be supported for a while. That's why I'm voting to relax the constraint. I will come up with the downgrade (alongside with other enhancements from @jonnynux supporting more V3 features).

**Comment by pwelch** [comment]
Okay, sounds good to me. I think we just need to drop it in the gemspec file and the GitHub CI file.

**Comment by pwelch** [comment]
Released v0.5.1: https://rubygems.org/gems/virustotal_api

Thanks as always for working on this!

**Comment by pwelch** [comment]
@crondaemon 

Released v0.5.1: https://rubygems.org/gems/virustotal_api

Thanks as always for working on this!
